# Generated by Django 4.2.8 on 2023-12-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolstoreapp', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('age', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=128)),
                ('phonenumber', models.IntegerField()),
                ('email', models.CharField(max_length=250)),
                ('address', models.TextField(blank=True)),
                ('purpose', models.CharField(choices=[('Male', 'Enquiry'), ('Return', 'Return')], max_length=128)),
                ('material', models.CharField(max_length=250)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolstoreapp.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolstoreapp.department')),
            ],
            options={
                'verbose_name': 'apply',
                'verbose_name_plural': 'apply',
                'ordering': ('name',),
            },
        ),
    ]
